<?php

use Illuminate\Database\Seeder;

class ProvinciaTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB :: table ( 'provincia' ) -> delete ();
        DB :: table ( 'provincia' ) -> insert ([
            
            
            ['id_provincia' =>1, 'pv_nombre' =>'CHACHAPOYAS', 'id_departamento' =>1,'pv_status' => '1'],
            ['id_provincia' =>2, 'pv_nombre' =>'BAGUA', 'id_departamento' =>1,'pv_status' => '1'],
            ['id_provincia' =>3, 'pv_nombre' =>'BONGARA', 'id_departamento' =>1,'pv_status' => '1'],
            ['id_provincia' =>4, 'pv_nombre' =>'CONDORCANQUI', 'id_departamento' =>1,'pv_status' => '1'],
            ['id_provincia' =>5, 'pv_nombre' =>'LUYA', 'id_departamento' =>1,'pv_status' => '1'],
            ['id_provincia' =>6, 'pv_nombre' =>'RODRIGUEZ DE MENDOZA', 'id_departamento' =>1,'pv_status' => '1'],
            ['id_provincia' =>7, 'pv_nombre' =>'UTCUBAMBA', 'id_departamento' =>1,'pv_status' => '1'],
            ['id_provincia' =>8, 'pv_nombre' =>'HUARAZ', 'id_departamento' =>2,'pv_status' => '1'],
            ['id_provincia' =>9, 'pv_nombre' =>'AIJA', 'id_departamento' =>2,'pv_status' => '1'],
            ['id_provincia' =>10, 'pv_nombre' =>'ANTONIO RAYMONDI', 'id_departamento' =>2,'pv_status' => '1'],
            ['id_provincia' =>11, 'pv_nombre' =>'ASUNCION', 'id_departamento' =>2,'pv_status' => '1'],
            ['id_provincia' =>12, 'pv_nombre' =>'BOLOGNESI', 'id_departamento' =>2,'pv_status' => '1'],
            ['id_provincia' =>13, 'pv_nombre' =>'CARHUAZ', 'id_departamento' =>2,'pv_status' => '1'],
            ['id_provincia' =>14, 'pv_nombre' =>'CARLOS FERMIN FITZCARRALD', 'id_departamento' =>2,'pv_status' => '1'],
            ['id_provincia' =>15, 'pv_nombre' =>'CASMA', 'id_departamento' =>2,'pv_status' => '1'],
            ['id_provincia' =>16, 'pv_nombre' =>'CORONGO', 'id_departamento' =>2,'pv_status' => '1'],
            ['id_provincia' =>17, 'pv_nombre' =>'HUARI', 'id_departamento' =>2,'pv_status' => '1'],
            ['id_provincia' =>18, 'pv_nombre' =>'HUARMEY', 'id_departamento' =>2,'pv_status' => '1'],
            ['id_provincia' =>19, 'pv_nombre' =>'HUAYLAS', 'id_departamento' =>2,'pv_status' => '1'],
            ['id_provincia' =>20, 'pv_nombre' =>'MARISCAL LUZURIAGA', 'id_departamento' =>2,'pv_status' => '1'],
            ['id_provincia' =>21, 'pv_nombre' =>'OCROS', 'id_departamento' =>2,'pv_status' => '1'],
            ['id_provincia' =>22, 'pv_nombre' =>'PALLASCA', 'id_departamento' =>2,'pv_status' => '1'],
            ['id_provincia' =>23, 'pv_nombre' =>'POMABAMBA', 'id_departamento' =>2,'pv_status' => '1'],
            ['id_provincia' =>24, 'pv_nombre' =>'RECUAY', 'id_departamento' =>2,'pv_status' => '1',],
            ['id_provincia' =>25, 'pv_nombre' =>'SANTA', 'id_departamento' =>2,'pv_status' => '1'],
            ['id_provincia' =>26, 'pv_nombre' =>'SIHUAS', 'id_departamento' =>2,'pv_status' => '1'],
            ['id_provincia' =>27, 'pv_nombre' =>'YUNGAY', 'id_departamento' =>2,'pv_status' => '1'],
            ['id_provincia' =>28, 'pv_nombre' =>'ABANCAY', 'id_departamento' =>3,'pv_status' => '1'],
            ['id_provincia' =>29, 'pv_nombre' =>'ANDAHUAYLAS', 'id_departamento' =>3,'pv_status' => '1'],
            ['id_provincia' =>30, 'pv_nombre' =>'ANTABAMBA', 'id_departamento' =>3,'pv_status' => '1'],
            ['id_provincia' =>31, 'pv_nombre' =>'AYMARAES', 'id_departamento' =>3,'pv_status' => '1'],
            ['id_provincia' =>32, 'pv_nombre' =>'COTABAMBAS', 'id_departamento' =>3,'pv_status' => '1'],
            ['id_provincia' =>33, 'pv_nombre' =>'CHINCHEROS', 'id_departamento' =>3,'pv_status' => '1'],
            ['id_provincia' =>34, 'pv_nombre' =>'GRAU', 'id_departamento' =>3,'pv_status' => '1'],
            ['id_provincia' =>35, 'pv_nombre' =>'AREQUIPA', 'id_departamento' =>4,'pv_status' => '1'],
            ['id_provincia' =>36, 'pv_nombre' =>'CAMANA', 'id_departamento' =>4,'pv_status' => '1'],
            ['id_provincia' =>37, 'pv_nombre' =>'CARAVELI', 'id_departamento' =>4,'pv_status' => '1'],
            ['id_provincia' =>38, 'pv_nombre' =>'CASTILLA', 'id_departamento' =>4,'pv_status' => '1'],
            ['id_provincia' =>39, 'pv_nombre' =>'CAYLLOMA', 'id_departamento' =>4,'pv_status' => '1'],
            ['id_provincia' =>40, 'pv_nombre' =>'CONDESUYOS', 'id_departamento' =>4,'pv_status' => '1'],
            ['id_provincia' =>41, 'pv_nombre' =>'ISLAY', 'id_departamento' =>4,'pv_status' => '1'],
            ['id_provincia' =>42, 'pv_nombre' =>'LA UNION', 'id_departamento' =>4,'pv_status' => '1'],
            ['id_provincia' =>43, 'pv_nombre' =>'HUAMANGA', 'id_departamento' =>5,'pv_status' => '1'],
            ['id_provincia' =>44, 'pv_nombre' =>'CANGALLO', 'id_departamento' =>5,'pv_status' => '1'],
            ['id_provincia' =>45, 'pv_nombre' =>'HUANCA SANCOS', 'id_departamento' =>5,'pv_status' => '1'],
            ['id_provincia' =>46, 'pv_nombre' =>'HUANTA', 'id_departamento' =>5,'pv_status' => '1'],
            ['id_provincia' =>47, 'pv_nombre' =>'LA MAR', 'id_departamento' =>5,'pv_status' => '1'],
            ['id_provincia' =>48, 'pv_nombre' =>'LUCANAS', 'id_departamento' =>5,'pv_status' => '1'],
            ['id_provincia' =>49, 'pv_nombre' =>'PARINACOCHAS', 'id_departamento' =>5,'pv_status' => '1'],
            ['id_provincia' =>50, 'pv_nombre' =>'PAUCAR DEL SARA SARA', 'id_departamento' =>5,'pv_status' => '1'],
            ['id_provincia' =>51, 'pv_nombre' =>'SUCRE', 'id_departamento' =>5,'pv_status' => '1'],
            ['id_provincia' =>52, 'pv_nombre' =>'VICTOR FAJARDO', 'id_departamento' =>5,'pv_status' => '1'],
            ['id_provincia' =>53, 'pv_nombre' =>'VILCAS HUAMAN', 'id_departamento' =>5,'pv_status' => '1'],
            ['id_provincia' =>54, 'pv_nombre' =>'CAJAMARCA', 'id_departamento' =>6,'pv_status' => '1'],
            ['id_provincia' =>55, 'pv_nombre' =>'CAJABAMBA', 'id_departamento' =>6,'pv_status' => '1'],
            ['id_provincia' =>56, 'pv_nombre' =>'CELENDIN', 'id_departamento' =>6,'pv_status' => '1'],
            ['id_provincia' =>57, 'pv_nombre' =>'CHOTA ', 'id_departamento' =>6,'pv_status' => '1'],
            ['id_provincia' =>58, 'pv_nombre' =>'CONTUMAZA', 'id_departamento' =>6,'pv_status' => '1'],
            ['id_provincia' =>59, 'pv_nombre' =>'CUTERVO', 'id_departamento' =>6,'pv_status' => '1'],
            ['id_provincia' =>60, 'pv_nombre' =>'HUALGAYOC', 'id_departamento' =>6,'pv_status' => '1'],
            ['id_provincia' =>61, 'pv_nombre' =>'JAEN', 'id_departamento' =>6,'pv_status' => '1'],
            ['id_provincia' =>62, 'pv_nombre' =>'SAN IGNACIO', 'id_departamento' =>6,'pv_status' => '1'],
            ['id_provincia' =>63, 'pv_nombre' =>'SAN MARCOS', 'id_departamento' =>6,'pv_status' => '1'],
            ['id_provincia' =>64, 'pv_nombre' =>'SAN PABLO', 'id_departamento' =>6,'pv_status' => '1'],
            ['id_provincia' =>65, 'pv_nombre' =>'SANTA CRUZ', 'id_departamento' =>6,'pv_status' => '1'],
            ['id_provincia' =>66, 'pv_nombre' =>'CALLAO', 'id_departamento' =>7,'pv_status' => '1'],
            ['id_provincia' =>67, 'pv_nombre' =>'CUSCO', 'id_departamento' =>8,'pv_status' => '1'],
            ['id_provincia' =>68, 'pv_nombre' =>'ACOMAYO', 'id_departamento' =>8,'pv_status' => '1'],
            ['id_provincia' =>69, 'pv_nombre' =>'ANTA', 'id_departamento' =>8,'pv_status' => '1'],
            ['id_provincia' =>70, 'pv_nombre' =>'CALCA', 'id_departamento' =>8,'pv_status' => '1'],
            ['id_provincia' =>71, 'pv_nombre' =>'CANAS', 'id_departamento' =>8,'pv_status' => '1'],
            ['id_provincia' =>72, 'pv_nombre' =>'CANCHIS', 'id_departamento' =>8,'pv_status' => '1'],
            ['id_provincia' =>73, 'pv_nombre' =>'CHUMBIVILCAS', 'id_departamento' =>8,'pv_status' => '1'],
            ['id_provincia' =>74, 'pv_nombre' =>'ESPINAR', 'id_departamento' =>8,'pv_status' => '1'],
            ['id_provincia' =>75, 'pv_nombre' =>'LA CONVENCION', 'id_departamento' =>8,'pv_status' => '1'],
            ['id_provincia' =>76, 'pv_nombre' =>'PARURO', 'id_departamento' =>8,'pv_status' => '1'],
            ['id_provincia' =>77, 'pv_nombre' =>'PAUCARTAMBO', 'id_departamento' =>8,'pv_status' => '1'],
            ['id_provincia' =>78, 'pv_nombre' =>'QUISPICANCHI', 'id_departamento' =>8,'pv_status' => '1'],
            ['id_provincia' =>79, 'pv_nombre' =>'URUBAMBA', 'id_departamento' =>8,'pv_status' => '1'],
            ['id_provincia' =>80, 'pv_nombre' =>'HUANCAVELICA', 'id_departamento' =>9,'pv_status' => '1'],
            ['id_provincia' =>81, 'pv_nombre' =>'ACOBAMBA', 'id_departamento' =>9,'pv_status' => '1'],
            ['id_provincia' =>82, 'pv_nombre' =>'ANGARAES', 'id_departamento' =>9,'pv_status' => '1'],
            ['id_provincia' =>83, 'pv_nombre' =>'CASTROVIRREYNA', 'id_departamento' =>9,'pv_status' => '1'],
            ['id_provincia' =>84, 'pv_nombre' =>'CHURCAMPA', 'id_departamento' =>9,'pv_status' => '1'],
            ['id_provincia' =>85, 'pv_nombre' =>'HUAYTARA', 'id_departamento' =>9,'pv_status' => '1'],
            ['id_provincia' =>86, 'pv_nombre' =>'TAYACAJA', 'id_departamento' =>9,'pv_status' => '1'],
            ['id_provincia' =>87, 'pv_nombre' =>'HUANUCO', 'id_departamento' =>10,'pv_status' => '1'],
            ['id_provincia' =>88, 'pv_nombre' =>'AMBO', 'id_departamento' =>10,'pv_status' => '1'],
            ['id_provincia' =>89, 'pv_nombre' =>'DOS DE MAYO', 'id_departamento' =>10,'pv_status' => '1'],
            ['id_provincia' =>90, 'pv_nombre' =>'HUACAYBAMBA', 'id_departamento' =>10,'pv_status' => '1'],
            ['id_provincia' =>91, 'pv_nombre' =>'HUAMALIES', 'id_departamento' =>10,'pv_status' => '1'],
            ['id_provincia' =>92, 'pv_nombre' =>'LEONCIO PRADO', 'id_departamento' =>10,'pv_status' => '1'],
            ['id_provincia' =>93, 'pv_nombre' =>'MARA&Ntilde;ON', 'id_departamento' =>10,'pv_status' => '1'],
            ['id_provincia' =>94, 'pv_nombre' =>'PACHITEA', 'id_departamento' =>10,'pv_status' => '1'],
            ['id_provincia' =>95, 'pv_nombre' =>'PUERTO INCA', 'id_departamento' =>10,'pv_status' => '1'],
            ['id_provincia' =>96, 'pv_nombre' =>'LAURICOCHA', 'id_departamento' =>10,'pv_status' => '1'],
            ['id_provincia' =>97, 'pv_nombre' =>'YAROWILCA', 'id_departamento' =>10,'pv_status' => '1'],
            ['id_provincia' =>98, 'pv_nombre' =>'ICA', 'id_departamento' =>11,'pv_status' => '1'],
            ['id_provincia' =>99, 'pv_nombre' =>'CHINCHA', 'id_departamento' =>11,'pv_status' => '1'],
            ['id_provincia' =>100, 'pv_nombre' =>'NAZCA', 'id_departamento' =>11,'pv_status' => '1'],
            ['id_provincia' =>101, 'pv_nombre' =>'PALPA', 'id_departamento' =>11,'pv_status' => '1'],
            ['id_provincia' =>102, 'pv_nombre' =>'PISCO', 'id_departamento' =>11,'pv_status' => '1'],
            ['id_provincia' =>103, 'pv_nombre' =>'HUANCAYO', 'id_departamento' =>12,'pv_status' => '1'],
            ['id_provincia' =>104, 'pv_nombre' =>'CONCEPCION', 'id_departamento' =>12,'pv_status' => '1'],
            ['id_provincia' =>105, 'pv_nombre' =>'CHANCHAMAYO', 'id_departamento' =>12,'pv_status' => '1'],
            ['id_provincia' =>106, 'pv_nombre' =>'JAUJA', 'id_departamento' =>12,'pv_status' => '1'],
            ['id_provincia' =>107, 'pv_nombre' =>'JUNIN', 'id_departamento' =>12,'pv_status' => '1'],
            ['id_provincia' =>108, 'pv_nombre' =>'SATIPO', 'id_departamento' =>12,'pv_status' => '1'],
            ['id_provincia' =>109, 'pv_nombre' =>'TARMA', 'id_departamento' =>12,'pv_status' => '1'],
            ['id_provincia' =>110, 'pv_nombre' =>'YAULI', 'id_departamento' =>12,'pv_status' => '1'],
            ['id_provincia' =>111, 'pv_nombre' =>'CHUPACA', 'id_departamento' =>12,'pv_status' => '1'],
            ['id_provincia' =>112, 'pv_nombre' =>'TRUJILLO', 'id_departamento' =>13,'pv_status' => '1'],
            ['id_provincia' =>113, 'pv_nombre' =>'ASCOPE', 'id_departamento' =>13,'pv_status' => '1'],
            ['id_provincia' =>114, 'pv_nombre' =>'BOLIVAR', 'id_departamento' =>13,'pv_status' => '1'],
            ['id_provincia' =>115, 'pv_nombre' =>'CHEPEN', 'id_departamento' =>13,'pv_status' => '1'],
            ['id_provincia' =>116, 'pv_nombre' =>'JULCAN', 'id_departamento' =>13,'pv_status' => '1'],
            ['id_provincia' =>117, 'pv_nombre' =>'OTUZCO', 'id_departamento' =>13,'pv_status' => '1'],
            ['id_provincia' =>118, 'pv_nombre' =>'PACASMAYO', 'id_departamento' =>13,'pv_status' => '1'],
            ['id_provincia' =>119, 'pv_nombre' =>'PATAZ', 'id_departamento' =>13,'pv_status' => '1'],
            ['id_provincia' =>120, 'pv_nombre' =>'SANCHEZ CARRION', 'id_departamento' =>13,'pv_status' => '1'],
            ['id_provincia' =>121, 'pv_nombre' =>'SANTIAGO DE CHUCO', 'id_departamento' =>13,'pv_status' => '1'],
            ['id_provincia' =>122, 'pv_nombre' =>'GRAN CHIMU', 'id_departamento' =>13,'pv_status' => '1'],
            ['id_provincia' =>123, 'pv_nombre' =>'VIRU', 'id_departamento' =>13,'pv_status' => '1'],
            ['id_provincia' =>124, 'pv_nombre' =>'CHICLAYO', 'id_departamento' =>14,'pv_status' => '1'],
            ['id_provincia' =>125, 'pv_nombre' =>'FERRE&Ntilde;AFE', 'id_departamento' =>14,'pv_status' => '1'],
            ['id_provincia' =>126, 'pv_nombre' =>'LAMBAYEQUE', 'id_departamento' =>14,'pv_status' => '1'],
            ['id_provincia' =>127, 'pv_nombre' =>'LIMA', 'id_departamento' =>15,'pv_status' => '1'],
            ['id_provincia' =>128, 'pv_nombre' =>'BARRANCA', 'id_departamento' =>15,'pv_status' => '1'],
            ['id_provincia' =>129, 'pv_nombre' =>'CAJATAMBO', 'id_departamento' =>15,'pv_status' => '1'],
            ['id_provincia' =>130, 'pv_nombre' =>'CANTA', 'id_departamento' =>15,'pv_status' => '1'],
            ['id_provincia' =>131, 'pv_nombre' =>'CA&Ntilde;ETE', 'id_departamento' =>15,'pv_status' => '1'],
            ['id_provincia' =>132, 'pv_nombre' =>'HUARAL', 'id_departamento' =>15,'pv_status' => '1'],
            ['id_provincia' =>133, 'pv_nombre' =>'HUAROCHIRI', 'id_departamento' =>15,'pv_status' => '1'],
            ['id_provincia' =>134, 'pv_nombre' =>'HUAURA', 'id_departamento' =>15,'pv_status' => '1'],
            ['id_provincia' =>135, 'pv_nombre' =>'OYON', 'id_departamento' =>15,'pv_status' => '1'],
            ['id_provincia' =>136, 'pv_nombre' =>'YAUYOS', 'id_departamento' =>15,'pv_status' => '1'],
            ['id_provincia' =>137, 'pv_nombre' =>'MAYNAS', 'id_departamento' =>16,'pv_status' => '1'],
            ['id_provincia' =>138, 'pv_nombre' =>'ALTO AMAZONAS', 'id_departamento' =>16,'pv_status' => '1'],
            ['id_provincia' =>139, 'pv_nombre' =>'LORETO', 'id_departamento' =>16,'pv_status' => '1'],
            ['id_provincia' =>140, 'pv_nombre' =>'MARISCAL RAMON CASTILLA', 'id_departamento' =>16,'pv_status' => '1'],
            ['id_provincia' =>141, 'pv_nombre' =>'REQUENA', 'id_departamento' =>16,'pv_status' => '1'],
            ['id_provincia' =>142, 'pv_nombre' =>'UCAYALI', 'id_departamento' =>16,'pv_status' => '1'],
            ['id_provincia' =>143, 'pv_nombre' =>'TAMBOPATA', 'id_departamento' =>17,'pv_status' => '1'],
            ['id_provincia' =>144, 'pv_nombre' =>'MANU', 'id_departamento' =>17,'pv_status' => '1'],
            ['id_provincia' =>145, 'pv_nombre' =>'TAHUAMANU', 'id_departamento' =>17,'pv_status' => '1'],
            ['id_provincia' =>146, 'pv_nombre' =>'MARISCAL NIETO', 'id_departamento' =>18,'pv_status' => '1'],
            ['id_provincia' =>147, 'pv_nombre' =>'GENERAL SANCHEZ CERRO', 'id_departamento' =>18,'pv_status' => '1'],
            ['id_provincia' =>148, 'pv_nombre' =>'ILO', 'id_departamento' =>18,'pv_status' => '1'],
            ['id_provincia' =>149, 'pv_nombre' =>'PASCO', 'id_departamento' =>19,'pv_status' => '1'],
            ['id_provincia' =>150, 'pv_nombre' =>'DANIEL ALCIDES CARRION', 'id_departamento' =>19,'pv_status' => '1'],
            ['id_provincia' =>151, 'pv_nombre' =>'OXAPAMPA', 'id_departamento' =>19,'pv_status' => '1'],
            ['id_provincia' =>152, 'pv_nombre' =>'PIURA', 'id_departamento' =>20,'pv_status' => '1'],
            ['id_provincia' =>153, 'pv_nombre' =>'AYABACA', 'id_departamento' =>20,'pv_status' => '1'],
            ['id_provincia' =>154, 'pv_nombre' =>'HUANCABAMBA', 'id_departamento' =>20,'pv_status' => '1'],
            ['id_provincia' =>155, 'pv_nombre' =>'MORROPON', 'id_departamento' =>20,'pv_status' => '1'],
            ['id_provincia' =>156, 'pv_nombre' =>'PAITA', 'id_departamento' =>20,'pv_status' => '1'],
            ['id_provincia' =>157, 'pv_nombre' =>'SULLANA', 'id_departamento' =>20,'pv_status' => '1'],
            ['id_provincia' =>158, 'pv_nombre' =>'TALARA', 'id_departamento' =>20,'pv_status' => '1'],
            ['id_provincia' =>159, 'pv_nombre' =>'SECHURA', 'id_departamento' =>20,'pv_status' => '1'],
            ['id_provincia' =>160, 'pv_nombre' =>'PUNO', 'id_departamento' =>21,'pv_status' => '1'],
            ['id_provincia' =>161, 'pv_nombre' =>'AZANGARO', 'id_departamento' =>21,'pv_status' => '1'],
            ['id_provincia' =>162, 'pv_nombre' =>'CARABAYA', 'id_departamento' =>21,'pv_status' => '1'],
            ['id_provincia' =>163, 'pv_nombre' =>'CHUCUITO', 'id_departamento' =>21,'pv_status' => '1'],
            ['id_provincia' =>164, 'pv_nombre' =>'EL COLLAO', 'id_departamento' =>21,'pv_status' => '1'],
            ['id_provincia' =>165, 'pv_nombre' =>'HUANCANE', 'id_departamento' =>21,'pv_status' => '1'],
            ['id_provincia' =>166, 'pv_nombre' =>'LAMPA', 'id_departamento' =>21,'pv_status' => '1'],
            ['id_provincia' =>167, 'pv_nombre' =>'MELGAR', 'id_departamento' =>21,'pv_status' => '1'],
            ['id_provincia' =>168, 'pv_nombre' =>'MOHO', 'id_departamento' =>21,'pv_status' => '1'],
            ['id_provincia' =>169, 'pv_nombre' =>'SAN ANTONIO DE PUTINA', 'id_departamento' =>21,'pv_status' => '1'],
            ['id_provincia' =>170, 'pv_nombre' =>'SAN ROMAN', 'id_departamento' =>21,'pv_status' => '1'],
            ['id_provincia' =>171, 'pv_nombre' =>'SANDIA', 'id_departamento' =>21,'pv_status' => '1'],
            ['id_provincia' =>172, 'pv_nombre' =>'YUNGUYO', 'id_departamento' =>21,'pv_status' => '1'],
            ['id_provincia' =>173, 'pv_nombre' =>'MOYOBAMBA', 'id_departamento' =>22,'pv_status' => '1'],
            ['id_provincia' =>174, 'pv_nombre' =>'BELLAVISTA', 'id_departamento' =>22,'pv_status' => '1'],
            ['id_provincia' =>175, 'pv_nombre' =>'EL DORADO', 'id_departamento' =>22,'pv_status' => '1'],
            ['id_provincia' =>176, 'pv_nombre' =>'HUALLAGA', 'id_departamento' =>22,'pv_status' => '1'],
            ['id_provincia' =>177, 'pv_nombre' =>'LAMAS', 'id_departamento' =>22,'pv_status' => '1'],
            ['id_provincia' =>178, 'pv_nombre' =>'MARISCAL CACERES', 'id_departamento' =>22,'pv_status' => '1'],
            ['id_provincia' =>179, 'pv_nombre' =>'PICOTA', 'id_departamento' =>22,'pv_status' => '1'],
            ['id_provincia' =>180, 'pv_nombre' =>'RIOJA', 'id_departamento' =>22,'pv_status' => '1'],
            ['id_provincia' =>181, 'pv_nombre' =>'SAN MARTIN', 'id_departamento' =>22,'pv_status' => '1'],
            ['id_provincia' =>182, 'pv_nombre' =>'TOCACHE', 'id_departamento' =>22,'pv_status' => '1'],
            ['id_provincia' =>183, 'pv_nombre' =>'TACNA', 'id_departamento' =>23,'pv_status' => '1'],
            ['id_provincia' =>184, 'pv_nombre' =>'CANDARAVE', 'id_departamento' =>23,'pv_status' => '1'],
            ['id_provincia' =>185, 'pv_nombre' =>'JORGE BASADRE', 'id_departamento' =>23,'pv_status' => '1'],
            ['id_provincia' =>186, 'pv_nombre' =>'TARATA', 'id_departamento' =>23,'pv_status' => '1'],
            ['id_provincia' =>187, 'pv_nombre' =>'TUMBES', 'id_departamento' =>24,'pv_status' => '1'],
            ['id_provincia' =>188, 'pv_nombre' =>'CONTRALMIRANTE VILLAR', 'id_departamento' =>24,'pv_status' => '1'],
            ['id_provincia' =>189, 'pv_nombre' =>'ZARUMILLA', 'id_departamento' =>24,'pv_status' => '1'],
            ['id_provincia' =>190, 'pv_nombre' =>'CORONEL PORTILLO', 'id_departamento' =>25,'pv_status' => '1'],
            ['id_provincia' =>191, 'pv_nombre' =>'ATALAYA', 'id_departamento' =>25,'pv_status' => '1'],
            ['id_provincia' =>192, 'pv_nombre' =>'PADRE ABAD', 'id_departamento' =>25,'pv_status' => '1'],
            ['id_provincia' =>193, 'pv_nombre' =>'PURUS', 'id_departamento' =>25,'pv_status' => '1']
                        
        ]);
    }
}
